In [1]:
import numpy as np

In [13]:
a =np.array([1,2,3,4,4,4,4,4,4,4,4,4], dtype='int32')
print(a)
y=np.float32(a)
print(y)
a.dtype

[1 2 3 4 4 4 4 4 4 4 4 4]
[1. 2. 3. 4. 4. 4. 4. 4. 4. 4. 4. 4.]


dtype('int32')

In [5]:
# unique function
c = np.array([1,2,3,4,4,6,5,8,5,4,3,8,5,4,7])
np.unique(c , return_index=True )               # return index to get index number on which data is placed

# also use Return_count to count that numbers
# flatten and ravel is used to convert 2d to 1d

(array([1, 2, 3, 4, 5, 6, 7, 8]),
 array([ 0,  1,  2,  3,  6,  5, 14,  7], dtype=int64))

In [15]:
# split function
np.split(a,3)

[array([1, 2, 3, 4]), array([4, 4, 4, 4]), array([4, 4, 4, 4])]

In [16]:
# insert function

a =np.array([1,2,3,4,6,4])
ins =np.insert(a ,(2,5),10)
print(ins)


[ 1  2 10  3  4  6 10  4]


In [11]:
# delete function

a =np.array([1,2,3,4,6,4])
dele = np.delete(a ,2)
print(dele)

[1 2 4 6 4]


In [6]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
b.dtype

dtype('float64')

In [8]:
# get a dimension
np.ndim(b)

2

In [9]:
# get a shape
b.shape

(2, 3)

In [15]:
x=a.reshape(2,3,2)
print(x)

# for converting 3d to 1d

y =x.reshape(-1)
print(y)

[[[1 2]
  [3 4]
  [4 4]]

 [[4 4]
  [4 4]
  [4 4]]]
[1 2 3 4 4 4 4 4 4 4 4 4]


In [16]:
# get type
a.dtype

dtype('int32')

In [17]:
# get size
a.itemsize      # as int increases size increases

4

In [19]:
# get total size
a.size*a.itemsize       # or by a.nbytes

48

In [20]:
# get a multi dimension array

arn = np.array([1,2,3,4], ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


### Changing and accesing specfic element,rows and columns

In [21]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# get a specfic element [r ,c]
a[1,4]

12

In [22]:
# get aspecfic row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
# get a specfic column
a[:,2]

array([ 3, 10])

In [24]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
# getting a little more fancy( start index: end index: step size)
a [0, 0:5:2]

array([1, 3, 5])

In [26]:
# change some row and column

# a[1,2] =20
# print(a)

a[: ,2] =[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 13 14]]


## 3d example

In [27]:
b =np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [33]:
b.ndim

3

In [32]:
# get specfic element (work outside in) # (set,row,column)


b[:,0 ,:]

array([[1, 2],
       [5, 6]])

In [ ]:
# replace

b[:,1,:]=[[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [ ]:
# arrange function
ar_rn =np.arange(4)
print(ar_rn)

[0 1 2 3]


## Iteration

In [38]:
var =np.array([1,2,3,4,5,6,7])
print(var)
print()
for i in var:
    print(i)

[1 2 3 4 5 6 7]

1
2
3
4
5
6
7


In [40]:
# for 2d array
var1 =np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(var1)
print()
for j in var1:
    print(j)
print()

for k in var1:                  # to saperate data within it
    for l in k:
        print(l)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[1 2 3 4 5]
[ 6  7  8  9 10]

1
2
3
4
5
6
7
8
9
10


In [41]:
# for 3 dimension

var3 =np.array([[[1,2,3,4,5],[6,7,8,9,10]]])
print(var3)
print()

for i in var3:                       # for loop
    for j in i: 
        for k in j:
            print(k)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]

1
2
3
4
5
6
7
8
9
10


In [43]:
var3 =np.array([[[1,2,3,4,5],[6,7,8,9,10]]])
print(var3)
print()

for i in np.nditer(var3):
    print(i)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]

1
2
3
4
5
6
7
8
9
10


In [44]:
# iterarion with indexing

var3 =np.array([[[1,2,3,4,5],[6,7,8,9,10]]])
print(var3)
print()

for i,d in np.ndenumerate(var3):
    print(i,d)


[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 1, 0) 6
(0, 1, 1) 7
(0, 1, 2) 8
(0, 1, 3) 9
(0, 1, 4) 10


### intializing differnt type of arrays and function


### search(to add ,subtract,divide)

In [52]:
var = np.array([1,2,3,4,8,4,3,2,1,9])

x = np.where( var > 2)
print(x)


(array([2, 3, 4, 5, 6, 9], dtype=int64),)


In [53]:
var = np.array([1,2,3,4,5,8,4,3,2,1])

x = np.searchsorted( var,6)
print(x)

5


In [54]:
# all is 0z matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [59]:
# all 1st matrix
np.ones((2,3,3), dtype="int32"  )

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [60]:
# any other number  #((shape),number)

np.full((3,2),  99 , dtype="float32") 

array([[99., 99.],
       [99., 99.],
       [99., 99.]], dtype=float32)

In [ ]:
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 13, 14]])

In [61]:
# any other number
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

### Random

In [62]:
# used to generate random value between 0 to 1
np.random.rand(4,2)                #  gives random data set

array([[0.86486792, 0.95642152],
       [0.18571288, 0.83653151],
       [0.25157744, 0.47209355],
       [0.67460981, 0.58404067]])

In [65]:
# this also gives random number between close to 0 whic may be positive and negative
np.random.randn(5)

array([-0.95864198,  0.63715866,  0.17098158, -0.27672601,  0.38137424])

In [75]:
# this also gives random number between 0.0 to 1.0 
np.random.ranf(4)

array([0.460487  , 0.10367399, 0.68510417, 0.11120282])

In [ ]:
# random integer values          
np.random.randint(7 ,size=(3,3))

array([[3, 0, 2],
       [0, 5, 2],
       [2, 4, 6]])

In [77]:
np.random.randint(1,20,5)

array([ 9, 11, 12,  8, 16])

# matrix

In [25]:
mat = np.matrix([[1,2,3,4],[5,6,7,8]])
print(mat)
print(type(mat))

mat2 = np.matrix([[1,2,3,4],[5,6,7,8]])
print(mat2+mat)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.matrix'>
[[ 2  4  6  8]
 [10 12 14 16]]


In [29]:
# for multiply
mat = np.matrix([[1,2],[5,6]])
print(mat.dot(mat))

[[11 14]
 [35 46]]


In [78]:
# for tanspose and swapaxes , inverse matrix
mate = np.matrix([[1,2],[5,6]])
print(mate)
# np.transpose(mate)
np.swapaxes(mate,0,1)
np.linalg.inv(mate)

[[1 2]
 [5 6]]


matrix([[-1.5 ,  0.5 ],
        [ 1.25, -0.25]])

In [37]:
# determinant

deter = np.matrix([[1,2,3],[5,6,7],[8,9,1]])
np.linalg.det(deter)

36.0

In [79]:
# identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# diagnol
ar_dia = np.eye(4)
print(ar_dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### linespace

In [ ]:
ar_lin = np.linspace(0,20 ,num=5 , dtype='int32')
print(ar_lin)

[ 0  5 10 15 20]


In [ ]:
# repeat array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


# making array using numpy function

In [ ]:
output =np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1]= 9
print(z)

output[1:4,1:4] = z         # in place this is exclusive value
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# function

In [81]:
# append function

l = []
for i in range(1,5):             # number of times value lenay hay 
    int_1 =int(input("enter"))        # value ko catch kenay kay liya aik variable banahay gay  
    l.append(int_1)              # is value ko list kay andar append krnay kay liya ya function use karay gay
 
print(np.array(l))

#  output may jo bhi function milta hay woh string may milta hay
# is liya input kay pichay integer laga kr inter may convert kar lay



[8 9 4 3]


### be carefull when copy arrays


In [82]:
# copy and view
a=np.array([1,2,3])
b=a.copy()           # use copy  for exact values of next  

b[0]=100
print(b)

[100   2   3]


## Mathematics

In [ ]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [84]:
a += 2
a

array([3, 4, 5])

In [85]:
np.cumsum(a)

array([ 3,  7, 12])

In [86]:
a-2

array([1, 2, 3])

In [87]:
a/2

array([1.5, 2. , 2.5])

In [88]:
a*2

array([ 6,  8, 10])

In [89]:
a ** 2      # a ka sqaureroot

array([ 9, 16, 25])

In [90]:
b = np.array([1,0,1,0])
a+b

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [ ]:
# take a sign
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

## Linear algebra

In [ ]:
a =np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)

np .matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
# find the determinant

c =np.identity(3)
print(c)
# np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### statistics

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats ,axis =1)

array([1, 4])

In [ ]:
np.max(stats , axis =0)

array([4, 5, 6])

In [ ]:
np.sum(stats)

21

### reorganizing arrays

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# Merge Array and concateante function

v1 =np.array([1,2,3,4,5])
v2 =np.array([6,7,8,9,1])

np.concatenate((v1,v2))

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1])

In [ ]:
# vertically stacking vectors
v1 =np.array([1,2,3,4,5])
v2 =np.array([6,7,8,9,1])         # use d for height

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1],
       [1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1]])

In [ ]:
# horizontal
h1 = np.ones([2,4])
h2 = np.zeros([2,2])

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## load data from file

In [ ]:
# filedata =np.genfromtxt('file.text', delimiter=',')
# filedata =filedata.astype('int32)

In [ ]:
# bolooen masking and advanced indexing
# np.any(file data > 50 ,axis=0  )  # it gives a boolean 
# ((filedata> 50) &  (filedata<100))   # it gives a boolean index




# filedata[filedata > 50 ,axis =0 ]    # it gives a inexing

In [ ]:
# you can index with the list in numpy

aa =np.array([1,2,3,4,5,6,7,8,9])
aa[[1,2,7]]

array([2, 3, 8])